---
- name: Import microsoft rpm key
  become: yes
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add VSCode repo
  become: yes
  yum_repository:
    name: vscode
    description: VSCode YUM repo
    file: vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Update package cache
  command: dnf check-update
  register: cmd_out
  failed_when: cmd_out.rc != 0 and cmd_out.rc != 100
  changed_when: false

- name: Install VSCode
  become: yes
  dnf:
    name: "{{ visual_studio_code_package }}"
    state: present